### ISSUE TITLE
博客园直接崩了

### ISSUE THREAD

**Issue by gaochaoqwe** [guangzan/awescnb#2]
用了你的第一个方法安装，现在我的博客已经进不去了，就一直闪烁，空白，根本进不去主页

**Comment by sky5454** [comment]
https://i.cnblogs.com
这是博客园后台管理页面，先使用默认皮肤吧

**Comment by guangzan** [comment]
> 用了你的第一个方法安装,现在我的博客已经进不去了,就一直闪烁,空白,根本进不去主页

抱歉，这么久没有回复您的消息。能否提供一些细节呢？另外，您可以加入 qq群 ，快速帮您解决问题。

**Comment by gaochaoqwe** [comment]
没关系的哈哈，我早就解决了，小问题



---原始邮件---
发件人: "guangzan"<notifications@github.com&gt;
发送时间: 2020年7月21日(周二) 下午3:37
收件人: "guangzan/awescnb"<awescnb@noreply.github.com&gt;;
抄送: "gaochaoqwe"<1484865109@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [guangzan/awescnb] 博客园直接崩了 (#2)




  
用了你的第一个方法安装,现在我的博客已经进不去了,就一直闪烁,空白,根本进不去主页
  
抱歉，这么久没有回复您的消息。能否提供一些细节呢？另外，您可以加入 qq群 ，快速帮您解决问题。
