### ISSUE TITLE
建议使用 git submodule

### ISSUE THREAD

**Issue by sky5454** [guangzan/awescnb#3]
建议使用 git 子项目，这样皮肤贡献者仓库能和本仓库分离，对面更新后你只要同步子模块 hash 号一下即可（建议通过 Watch Release 订阅更新）。

不然当前的种种限制，可能导致没什么人会贡献皮肤的

**Comment by sky5454** [comment]
例子： https://github.com/AFan-z/BookManage

**Comment by guangzan** [comment]
抱歉，这么久没有回复您。感谢您的建议，我在学习如何这样做。另外，本项目使用的是 Gitee 的 Pages 服务，我不知道做是否会有影响。

**Comment by guangzan** [comment]
谢谢建议。其实没什么限制，我试着将主题 silence 移植进来只花了不到 30 分钟。通过 pr 贡献代码完全足够了。
