### ISSUE TITLE
图片无法加载

### ISSUE THREAD

**Issue by fengmao31** [guangzan/awescnb#7]
图片无法加载
GitHub那些仓库的链接怎么添加
自己下载js改？

**Comment by guangzan** [comment]
哪里的图片呀

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/105024509-23a47f80-5a87-11eb-8391-e9f53b034a4c.png)

**Comment by guangzan** [comment]
https://www.yuque.com/awescnb/user/rycpvv#cba0d619
基本配置>avatar

**Comment by fengmao31** [comment]
老哥感动。感谢回复。
看明白了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "GZ"<notifications@github.com&gt;; 
发送时间: 2021年2月26日(星期五) 晚上9:27
收件人: "guangzan/awescnb"<awescnb@noreply.github.com&gt;; 
抄送: "魔法猫"<2389442920@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [guangzan/awescnb] 图片无法加载 (#7)





 
https://www.yuque.com/awescnb/user/rycpvv#cba0d619
 基本配置&gt;avatar
